server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:grade-submission

logging:
  level:
    org:
      springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  message: 'Hello-Its-Aparna'
